name: flutter_swiper
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 1.1.6
author: JZoom <jzoom8112@gmail.com>
homepage: https://github.com/jzoom/flutter_swiper

dependencies:
  flutter:
    sdk: flutter

  transformer_page_view:
    git:
      url: https://github.com/whosmyqueen/transformer_page_view.git
      ref: master
  flutter_page_indicator:
    git:
      url: https://github.com/whosmyqueen/flutter_page_indicator.git
      ref: master

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
